"""
Django settings for blogproject project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3q^p@e5hiqvqfhsi^62lx02cmf=%)39u!v$kypi$nig#_jd81f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['www.summerdawn.top','www.summerdawn.xyz','summerdawn.top','summerdawn.xyz','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_comments',
    'blog',
    'ckeditor',
    'ckeditor_uploader',
    #'DjangoUeditor',
    ]
SITE_ID = 1

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_BROWSE_SHOW_DIRS=True
CKEDITOR_RESTRICT_BY_DATE=True
#CKEDITOR_FILENAME_GENERATOR =

CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_CONFIGS = {
    'awesome_ckeditor': {

        #'toolbar': 'Basic',
        'language' : 'zh-cn',
        'image_previewText' : ' ',
        'mathJaxLib':'https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML',
        'codeSnippet_theme' : 'github',
        'toolbar': 'Custom',
        'toolbar_Custom':[

        ['Styles', 'Format', '-','Bold', 'Italic', 'Underline', 'Strike','Blockquote', 'SpellChecker'],
        [ 'Outdent', 'Indent', '-','JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],

        ['Link', 'Unlink', 'Anchor',],

        ['Image', 'Flash', 'Html5video','Table', 'HorizontalRule','CodeSnippet'],

        ['TextColor', 'BGColor'],

        ['Subscript', 'Superscript', '-','NumberedList', 'BulletedList', '-','Emojione', 'SpecialChar','Mathjax'], [ 'RemoveFormat''-','Source','Preview','Maximize'],['PasteFromWord','PasteText','CreateDiv'],
        [ 'Undo', 'Redo'],
    ],

        'extraPlugins':','.join(['codesnippet','widget','lineutils','widgetselection','mathjax','html5video','tableresize','emojione']),

},
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blogproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blogproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

#STATIC_URL = '/static/'


#QINIU_ACCESS_KEY = 'XT39KsbPcEzDOoYwCOhLlmyK5Sznf2Pc074_fjZA'
#QINIU_SECRET_KEY = 'FsUOEr7KdQs7PdKXPW_H2s-V1UiS4sCX9YB9fMhD'
#QINIU_BUCKET_NAME = 'yijijiegou'
#QINIU_BUCKET_DOMAIN = 'ooxetgtvz.bkt.clouddn.com'
#QINIU_SECURE_URL = False      #使用http

QINIU_ACCESS_KEY= 'XT39KsbPcEzDOoYwCOhLlmyK5Sznf2Pc074_fjZA'
QINIU_SECRET_KEY= 'FsUOEr7KdQs7PdKXPW_H2s-V1UiS4sCX9YB9fMhD'
QINIU_BUCKET_NAME= 'summerdawn'
QINIU_BUCKET_DOMAIN= 'oox9jbpeq.bkt.clouddn.com'
DEFAULT_FILE_STORAGE = 'qiniustorage.backends.QiniuMediaStorage'

PREFIX_URL = 'http://'

#MEDIA_URL = PREFIX_URL + QINIU_BUCKET_DOMAIN + '/media/'
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#DEFAULT_FILE_STORAGE = 'qiniustorage.backends.QiniuMediaStorage'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# 公共的 static 文件，比如 jquery.js 可以放这里，这里面的文件夹不能包含 STATIC_ROOT
STATICFILES_DIRS = (os.path.join(BASE_DIR, "common_static"),)

# upload folder
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')